### PR TITLE
Add deviceScaleFactor option

### PR DESCRIPTION
**Pull request by chaffeqa**
This is a very needed option in taking screenshots.

### CODE REVIEW

**Review by chaffeqa — COMMENTED** [review]
This is a very needed option in taking screenshots.

**Comment by jamesonhill** [comment]
I very much need this as well. It's supported in puppeteer.

**Comment by joelgriffith** [comment]
Open to merging if anyone wants to look into the failures?

**Comment by chaffeqa** [comment]
how do I get the checks to rerun?

**Review by joelgriffith — APPROVED** [review]

**Pull request merged**
