### PR TITLE
Remove screencast extension

### PR DESCRIPTION
**Pull request by marpo60**
Tasks:
- [X] Record Video
Audio Stream is not working, Im not able to enable by default the Share Audio option that is shown on the screen picker dialog 
- [ ] Record Audio Stream

Related:
https://bugs.chromium.org/p/chromium/issues/detail?id=326740#c105
https://bugs.chromium.org/p/chromium/issues/detail?id=896333

### CODE REVIEW

**Comment by joelgriffith** [comment]
Nice, this is looking good!

**Comment by html5maker** [comment]
Why not just changing **audio: true**?
const desktopStream = await navigator.mediaDevices.getDisplayMedia({video: true, audio: **false**});

**Comment by joelgriffith** [comment]
Wondering if `--autoplay-policy=no-user-gesture-required` might have an effect here...

**Comment by marpo60** [comment]
@html5maker That would show the audio checkbox in the UI picker.

@joelgriffith Will try that and get back

**Comment by html5maker** [comment]
Actually I don't see any use-case for recording the screencast from chrome webpage with audio...
Record a youtube video? :) Makes no sense...
I think that it should be released without audio and for the sound recording the old extension method can be used...

**Comment by joelgriffith** [comment]
Unfortunately a caveat to this approach is that it won't continue to record over a page-navigation or reload :/ I think we're essentially stuck with an extension until such a time that puppeteer has a better mechanism.

**Comment by marpo60** [comment]
Make sense, thanks @joelgriffith

**Pull request closed without merging**
