### PR TITLE
Support webdriver `browserless:token`

### LINKED ISSUE #1343: Make `browserless.token` a valid W3C Capability
I'm just forward the issue from [browserless docs](https://github.com/browserless/docs/issues/1). I think it's more appropriate to make an issue here.

Summary: could not supply `browserless.token` to Webdriver.io because it's not a W3C-standards capability.

Proposed solution: deprecate `browserless.token` and instead use `browserless:token` for W3C conformance.

### PR DESCRIPTION
**Pull request by osddeitf**
Fix #1343.

### CODE REVIEW

**Comment by osddeitf** [comment]
Some how the `Chrome Edge CI / build` stage have failed, how could it rerun?

**Comment by joelgriffith** [comment]
Yup, rerunning now. Been kind of flaky recently

**Comment by joelgriffith** [comment]
Finally green! I’ll do one more manual check tomorrow, but this looks great. Thanks again for the PR!

**Comment by osddeitf** [comment]
Thanks, I'd like it merge soon so that I can use latest `browserless/chrome` image for my workflow.

**Comment by joelgriffith** [comment]
Cool, merged. PR and tests cover everything. There’s a few other parameters that need to be handled, but can happen in a follow up PR

**Comment by osddeitf** [comment]
I have another question, when will the [docs](https://docs.browserless.io/docs/selenium-library.html) be updated? Please update it in the next release.

**Pull request merged**
