### PR TITLE
Add support for incognito mode

### PR DESCRIPTION
**Pull request by kadaan**
Support for #369

### CODE REVIEW

**Comment by joelgriffith** [comment]
Apologies as I'm still trying to wrap my head around this. Is the use-case:

- Setting up a docker image to run with prebooting and keepalive
- User runs a function, done.
- User runs another function and gets a browser context that is not clean?

It seems to me that this is somewhat desired behavior as prebooting and keepalive are going to re-use the same browsers, so you're more-or-less expecting this behavior?

**Comment by kadaan** [comment]
No worries. The use case is:
* Setting up a docker image to run with prebooting and keepalive
* User runs a function, done.
* User runs another function and gets a browser context is completely clean?

From what I can tell, currently, with preboot and keepalive, second function calls would have access to cookies, local storage, etc. from the first.

**Comment by joelgriffith** [comment]
I can definitely see both sides of it. Right now, for other integrations, that behavior is more or less correct (stateful stuff like cookies and local-storage will be there for the next session). Puppeteer doesn't really have a way to "reset" the browser back to a clean slate, which unfortunately means consumers will have to do this manually for puppeteer.

Let me think a bit more about it and we'll go from there. This is a tricky one!

**Comment by kadaan** [comment]
Also, the change is opt-in. It is controlled at start up of the container.

**Comment by kadaan** [comment]
For reference: https://stackoverflow.com/questions/50804198/what-is-a-browsercontext-in-the-node-library-puppeteer

**Comment by joelgriffith** [comment]
That’s fair, I would you thinking naming it something more specific to “function”? Since we have a large number of env variables I think we’re going to need to start namespacing them, or making them fairly granular.

**Comment by kadaan** [comment]
Cool. I can do that when I am back from holiday.

**Comment by kadaan** [comment]
@joelgriffith Added a "function" prefix to the setting

**Pull request merged**
