### PR TITLE
build: Use Ubuntu 22.10

### PR DESCRIPTION
**Pull request by Kikobeats**
just testing in the edge 😛

I'm aiming for using this version because it makes possible to use `ffmpeg@5`

### CODE REVIEW

**Comment by joelgriffith** [comment]
>E: The repository 'http://archive.canonical.com/ubuntu kinetic Release' does not have a Release file.

Looks like some dependency is straggling behind a bit. Maybe retry in a week?

**Comment by Kikobeats** [comment]
@joelgriffith yes, let's retry in a week 🙂

**Comment by joelgriffith** [comment]
@Kikobeats can you merge master and push?

**Comment by Kikobeats** [comment]
done! let see 🙏

**Comment by joelgriffith** [comment]
Not sure why that chromium test keeps failing… I’d be open to any PR that fixes it?

**Comment by Kikobeats** [comment]
@joelgriffith can you try to re-test?

**Comment by joelgriffith** [comment]
@Kikobeats could you re-merge master and push?

**Comment by Kikobeats** [comment]
done

**Comment by andyMrtnzP** [comment]
@Kikobeats sorry for the back and forth with this one. We tested it internally and it's all good! Could you re-merge it one last time?

**Comment by Kikobeats** [comment]
@andyMrtnzP done

**Comment by andyMrtnzP** [comment]
We're closing this one and opening https://github.com/browserless/chrome/pull/3167 based on this branch @Kikobeats

**Pull request closed without merging**
