### PR TITLE
Move to node 14

### PR DESCRIPTION
**Pull request by joelgriffith**

### CODE REVIEW

**Comment by Kikobeats** [comment]
@joelgriffith not sure why the `Build the chrome-stable image` step failed 🤔

**Comment by joelgriffith** [comment]
Actually, both fail, and it has to do with chromedriver not working properly on node 14...

**Comment by Kikobeats** [comment]
@joelgriffith 

The CI error is a totally different not related thing:

```
manifest for browserless/base:1.6.0 not found: manifest unknown: manifest unknown
Sending build context to Docker daemon  2.335MB

Step 1/26 : FROM browserless/base:1.6.0
##[error]Process completed with exit code 1.
```

maybe the version number needs to be republished?

**Comment by joelgriffith** [comment]
Closing in favor of https://github.com/browserless/chrome/pull/951

**Pull request closed without merging**
