### PR TITLE
Add prometheus support

### PR DESCRIPTION
**Pull request by kadaan**
Support for #357

### CODE REVIEW

**Comment by kadaan** [comment]
Metrics look like:
```
$ curl http://localhost:3000/prometheus
# HELP http_request_duration_seconds duration histogram of http responses labeled with: status_code, method, path
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{le="0.003",status_code="200",method="POST",path="/function"} 0
http_request_duration_seconds_bucket{le="0.03",status_code="200",method="POST",path="/function"} 0
http_request_duration_seconds_bucket{le="0.1",status_code="200",method="POST",path="/function"} 0
http_request_duration_seconds_bucket{le="0.3",status_code="200",method="POST",path="/function"} 0
http_request_duration_seconds_bucket{le="1.5",status_code="200",method="POST",path="/function"} 1
http_request_duration_seconds_bucket{le="10",status_code="200",method="POST",path="/function"} 1
http_request_duration_seconds_bucket{le="+Inf",status_code="200",method="POST",path="/function"} 1
http_request_duration_seconds_sum{status_code="200",method="POST",path="/function"} 1.426241158
http_request_duration_seconds_count{status_code="200",method="POST",path="/function"} 1
http_request_duration_seconds_bucket{le="0.003",status_code="200",method="GET",path="/metrics"} 0
http_request_duration_seconds_bucket{le="0.03",status_code="200",method="GET",path="/metrics"} 0
http_request_duration_seconds_bucket{le="0.1",status_code="200",method="GET",path="/metrics"} 1
http_request_duration_seconds_bucket{le="0.3",status_code="200",method="GET",path="/metrics"} 1
http_request_duration_seconds_bucket{le="1.5",status_code="200",method="GET",path="/metrics"} 1
http_request_duration_seconds_bucket{le="10",status_code="200",method="GET",path="/metrics"} 1
http_request_duration_seconds_bucket{le="+Inf",status_code="200",method="GET",path="/metrics"} 1
http_request_duration_seconds_sum{status_code="200",method="GET",path="/metrics"} 0.038295886
http_request_duration_seconds_count{status_code="200",method="GET",path="/metrics"} 1

# HELP process_cpu_user_seconds_total Total user CPU time spent in seconds.
# TYPE process_cpu_user_seconds_total counter
process_cpu_user_seconds_total 0.23225099999999999 1570136940347

# HELP process_cpu_system_seconds_total Total system CPU time spent in seconds.
# TYPE process_cpu_system_seconds_total counter
process_cpu_system_seconds_total 0.044808999999999995 1570136940347

# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.27706 1570136940347

# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1570136910

# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 55705600 1570136940347

# HELP nodejs_eventloop_lag_seconds Lag of event loop in seconds.
# TYPE nodejs_eventloop_lag_seconds gauge
nodejs_eventloop_lag_seconds 0.000150607 1570136940347

# HELP nodejs_active_handles Number of active libuv handles grouped by handle type. Every handle type is C++ class name.
# TYPE nodejs_active_handles gauge
nodejs_active_handles{type="WriteStream"} 2 1570136940347
nodejs_active_handles{type="Server"} 1 1570136940347

# HELP nodejs_active_handles_total Total number of active handles.
# TYPE nodejs_active_handles_total gauge
nodejs_active_handles_total 3 1570136940347

# HELP nodejs_active_requests Number of active libuv requests grouped by request type. Every request type is C++ class name.
# TYPE nodejs_active_requests gauge

# HELP nodejs_active_requests_total Total number of active requests.
# TYPE nodejs_active_requests_total gauge
nodejs_active_requests_total 0 1570136940347

# HELP nodejs_heap_size_total_bytes Process heap size from node.js in bytes.
# TYPE nodejs_heap_size_total_bytes gauge
nodejs_heap_size_total_bytes 26550272 1570136940347

# HELP nodejs_heap_size_used_bytes Process heap size used from node.js in bytes.
# TYPE nodejs_heap_size_used_bytes gauge
nodejs_heap_size_used_bytes 23508048 1570136940347

# HELP nodejs_external_memory_bytes Nodejs external memory size in bytes.
# TYPE nodejs_external_memory_bytes gauge
nodejs_external_memory_bytes 3676658 1570136940347

# HELP nodejs_heap_space_size_total_bytes Process heap space size total from node.js in bytes.
# TYPE nodejs_heap_space_size_total_bytes gauge
nodejs_heap_space_size_total_bytes{space="read_only"} 524288 1570136940347
nodejs_heap_space_size_total_bytes{space="new"} 1048576 1570136940347
nodejs_heap_space_size_total_bytes{space="old"} 19521536 1570136940347
nodejs_heap_space_size_total_bytes{space="code"} 688128 1570136940347
nodejs_heap_space_size_total_bytes{space="map"} 1576960 1570136940347
nodejs_heap_space_size_total_bytes{space="large_object"} 3141632 1570136940347
nodejs_heap_space_size_total_bytes{space="code_large_object"} 49152 1570136940347
nodejs_heap_space_size_total_bytes{space="new_large_object"} 0 1570136940347

# HELP nodejs_heap_space_size_used_bytes Process heap space size used from node.js in bytes.
# TYPE nodejs_heap_space_size_used_bytes gauge
nodejs_heap_space_size_used_bytes{space="read_only"} 31712 1570136940347
nodejs_heap_space_size_used_bytes{space="new"} 848656 1570136940347
nodejs_heap_space_size_used_bytes{space="old"} 18172048 1570136940347
nodejs_heap_space_size_used_bytes{space="code"} 286016 1570136940347
nodejs_heap_space_size_used_bytes{space="map"} 1044320 1570136940347
nodejs_heap_space_size_used_bytes{space="large_object"} 3123936 1570136940347
nodejs_heap_space_size_used_bytes{space="code_large_object"} 3456 1570136940347
nodejs_heap_space_size_used_bytes{space="new_large_object"} 0 1570136940347

# HELP nodejs_heap_space_size_available_bytes Process heap space size available from node.js in bytes.
# TYPE nodejs_heap_space_size_available_bytes gauge
nodejs_heap_space_size_available_bytes{space="read_only"} 492264 1570136940347
nodejs_heap_space_size_available_bytes{space="new"} 199296 1570136940347
nodejs_heap_space_size_available_bytes{space="old"} 949744 1570136940347
nodejs_heap_space_size_available_bytes{space="code"} 28032 1570136940347
nodejs_heap_space_size_available_bytes{space="map"} 103896 1570136940347
nodejs_heap_space_size_available_bytes{space="large_object"} 0 1570136940347
nodejs_heap_space_size_available_bytes{space="code_large_object"} 0 1570136940347
nodejs_heap_space_size_available_bytes{space="new_large_object"} 1047952 1570136940347

# HELP nodejs_version_info Node.js version info.
# TYPE nodejs_version_info gauge
nodejs_version_info{version="v12.4.0",major="12",minor="4",patch="0"} 1
```

**Comment by joelgriffith** [comment]
Looks great, thanks!

**Comment by alikhil** [comment]
Hi! How to enable prometheus metrics? Seems like they should be enabled by default, by when I try to get them, I get the following:

```
curl http://localhost:3000/prometheus?token=mytoken
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /prometheus</pre>
</body>
</html>
```

I am using browserless/chrome@sha256:6e1c5175c0fed108a6ed51a629ee5a55cb23c9cabd30bf16ce1cd1751dca2679

**Comment by howiezhao** [comment]
Is there any relevant documentation for this, I didn't find it

**Pull request merged**
