### PR TITLE
Ready and liveness checks

### PR DESCRIPTION
**Pull request by dantheman999301**
@joelgriffith These were the two endpoints we talked about. For some reason I cannot run either the tests or the application locally because I get an error:
`Error: Cannot find module '../hosts.json'`.

Not sure why the router isn't picking up the two new endpoints. I assume I've missed a step in wiring this up somewhere. Any ideas?

### CODE REVIEW

**Comment by joelgriffith** [comment]
@dantheman999301 yup, kind of a wonky thing on our end, just do `npm run post-install`. It'll generate that file for you

**Comment by dantheman999301** [comment]
Ah thanks. Annoyingly it looks like that command doesn't play nicely with Windows. Might have to play around with getting the development environment running in Docker as well.

**Comment by dantheman999301** [comment]
```
❯ npm run post-install

> browserless-chrome@1.40.1 post-install C:\Users\dedwa\dev\personal\browserless
> npm run external && npm run symlink-chrome && npm run meta


> browserless-chrome@1.40.1 external C:\Users\dedwa\dev\personal\browserless
> rimraf debugger/devtools && node ./scripts/install-external-deps.js

Downloading chromium for revision 800071
Downloading chromedriver for revision 800071
Downloading devtools assets for revision 800071
Error unpacking assets:
undefined
undefined
```

`undefined` for both parts of the error message, but so I just made it print the whole error...

```
"Timeout waiting for file C:\\Users\\dedwa\\AppData\\Local\\Temp\\browserless-devtools-1603903014133\\chromedriver_win32\\chromedriver"
```

Maybe not Windows related after all. What's interesting is that it does not take long for that to happen, 4-5 seconds maybe?

**Comment by joelgriffith** [comment]
How about the Windows linux subsystem? That's what I've been using recently on windows-dev

**Comment by joelgriffith** [comment]
Going to close this for now due to inactivity. Feel free to re-open when ready.

**Pull request closed without merging**
