### PR TITLE
Fix for #1571

### PR DESCRIPTION
**Pull request by kadaan**
Allow stealth in defaultLaunchArgs to be configured via DEFAULT_STEALTH environment variable

### CODE REVIEW

**Comment by kadaan** [comment]
Fixes #1571

**Comment by kadaan** [comment]
@joelgriffith Any idea about these test failures?

**Comment by joelgriffith** [comment]
Yeah, these have been kind of flaky recently due to the memory/cpu intensity. I'll take a look at them.

**Comment by joelgriffith** [comment]
@kadaan if you merge/rebase against `master` the tests should be a bit more resilient.

**Comment by howiezhao** [comment]
@joelgriffith  Should it be updated to https://docs.browserless.io/docs/docker.html ?

**Pull request merged**
