### PR TITLE
Upgrade to node.js 12

### PR DESCRIPTION
**Pull request by amotzte**
node.js 12 is now officially LTS

### CODE REVIEW

**Comment by joelgriffith** [comment]
I'm going to pull this down and see if there's any performance regressions (which happened with the transition to 10)

**Comment by amotzte** [comment]
Thanks @joelgriffith. Node.js are reporting a big improvement in performance in node.js 12 ([CHANGELOG_V12](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md)). Would be interesting to see your results.

**Comment by joelgriffith** [comment]
Looking good! Seems that Node 12 had a wider range of stats (here's my crude stress script):

```js
const puppeteer = require('puppeteer');
const _ = require('lodash');

const num = 100;
let runs = 0;
const stats = [];


async function run() {
  let browser = null;

  const start = Date.now();

  try {
    browser = await puppeteer.connect({
      browserWSEndpoint: `ws://localhost:3000`,
    });

    const [page] = await browser.pages();
    await page.goto('https://example.com', { waitUntil: 'networkidle0' });
    await page.pdf();
  } catch (e) {
    console.error(`Saw error:`, e);
  } finally {
    stats.push(Date.now() - start);

    if (browser) {
      browser.close();
    }

    if (runs < num) {
      console.log(runs);
      runs++;
      return run();
    } else {
      console.log(_.min(stats), _.max(stats));
    }
  }
}

(async() => {
  for (var i = 0; i < 10; i++) {
    run();
  }
})()

```
I'm test that 10 concurrent sessions (running up to 100), and printing the example.com site. So there's a lot of external's that our outside of our control. Stats for 3 runs of each are:

```
Node 12
- 1882 3869
- 2363 5409
- 2049 4736

Node 10
- 2083 3940
- 1985 3751
- 2078 3582
```

I might do some more isolated tests locally to see if that hones it down further.

The biggest thing I noticed is that 12 doesn't use as much RAM or CPU for this workload, which is encouraging.

**Comment by amotzte** [comment]
@joelgriffith thanks for merging this. 
I see that a latest version was created for docker ```browserless/chrome``` but it seems to still be using the old ```browserless/base``` (node.js 10).
Is there anything else we need to do in order to get the lastest using node 12?

**Comment by Kikobeats** [comment]
Any plan for release a new tag with this? 🙂

**Pull request merged**
