### PR TITLE
Use Node.js 18 LTS

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by andyMrtnzP** [comment]
Thanks! It's going to fail since we're having some troubles with the Docker image building process. I'll ping you when the fix is ready to give it another try :)

**Comment by andyMrtnzP** [comment]
@Kikobeats you can give it a try now!

**Comment by Kikobeats** [comment]
@andyMrtnzP I can't re-run; can you?

**Comment by andyMrtnzP** [comment]
Ah, sorry, you'll have to merge master into the branch

**Comment by Kikobeats** [comment]
@andyMrtnzP its green!

**Review by joelgriffith — APPROVED** [review]
LGTM -- I checked our CI pipeline to see if we're statically referencing specific node version, and we _mostly_ use docker to abstract that away.

So, in short, if CI is good then I'm good 🟢

**Pull request merged**
